apiVersion: v1
values:
  images:
    usermgt: registry.cloudogu.com/official/usermgt:1.21.0-5
    chownInitImage: busybox:1.36
patches:
  values.yaml:
    additionalImages:
      chownInitImage: "{{ .images.chownInitImage }}"
    image:
      registry: "{{ registryFrom .images.usermgt }}"
      repository: "{{ repositoryFrom .images.usermgt }}"
      tag: "{{ tagFrom .images.usermgt }}"
